
#define PLANETFIRSTSYLLABLE 34
#define PLANETMIDDLESYLLABLE 22
#define PLANETLASTSYLLABLE 39

#define ARTICLE_TAVERN_NUMBER 4
#define FIRST_WORD_TAVERN_NUMBER 23
#define SECOND_WORD_TAVERN_NUMBER 31

#define DWARF_FEMALE_FIRST_SYLLABLE 144
#define DWARF_FEMALE_SECOND_SYLLABLE 49

#define DWARF_MALE_FIRST_SYLLABLE 163
#define DWARF_MALE_SECOND_SYLLABLE 49
